'use client';
import {useEffect,useRef} from 'react';
export default function Particles({mode=0,energy=50,paused=false,className=''}:{mode?:number,energy?:number,paused?:boolean,className?:string}){
 const redraw=useRef<(()=>void)|null>(null);const ref=useRef<HTMLCanvasElement>(null),props=useRef({mode,energy,paused});props.current={mode,energy,paused};useEffect(()=>{redraw.current?.();},[mode,energy,paused]);
 useEffect(()=>{const c=ref.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;let frame=0,vis=false,px=-10,py=-10,t=0,last=0;const reduce=matchMedia('(prefers-reduced-motion: reduce)');const draw=(now:number)=>{frame=requestAnimationFrame(draw);if(!vis||document.hidden)return;if(props.current.paused&&last)return;const dpr=Math.min(devicePixelRatio,1.5),w=c.clientWidth,h=c.clientHeight;if(c.width!==w*dpr||c.height!==h*dpr){c.width=w*dpr;c.height=h*dpr;}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#07060c';ctx.fillRect(0,0,w,h);if(!reduce.matches)t+=Math.min((now-last)/1000||.016,.04)*(.2+props.current.energy/120);last=now;const cols=w<500?42:78,rows=w<500?24:38;
 for(let i=0;i<cols;i++)for(let j=0;j<rows;j++){let x=(i/(cols-1)-.5),y=(j/(rows-1)-.5),z=0;const m=props.current.mode;if(m===0){z=Math.sin(x*9+t)*Math.cos(y*7+t*.6)*.22;y+=z*.45;}else if(m===1){const a=i/cols*Math.PI*2,b=j/rows*Math.PI;z=Math.sin(b)*Math.cos(a+t)*.5;x=Math.sin(b)*Math.sin(a+t)*.46;y=Math.cos(b)*.46;}else{z=Math.sin(x*7+y*5+t)*.22;y+=Math.sin(x*8+t)*.18;}
 let sx=w*.5+x*w*.9,sy=h*.5+y*h*.7+z*h*.3;const dx=sx-px*w,dy=sy-py*h,dist=Math.hypot(dx,dy);if(dist<100&&dist>0){const force=(1-dist/100)*28;sx+=dx/dist*force;sy+=dy/dist*force;}const a=.3+(z+.3)*.9;ctx.fillStyle=m===2?`rgba(203,143,255,${a})`:`rgba(${145+Math.round(z*110)},${120+Math.round(z*70)},255,${a})`;ctx.beginPath();ctx.arc(sx,sy,(.65+(z+.3)*1.1)*(w<500?.8:1),0,Math.PI*2);ctx.fill();}
 if(reduce.matches)cancelAnimationFrame(frame);};redraw.current=()=>{if(reduce.matches){last=0;cancelAnimationFrame(frame);draw(performance.now());}};const observer=new IntersectionObserver(([e])=>{vis=e.isIntersecting;if(vis&&reduce.matches)draw(performance.now());},{rootMargin:'100px'});observer.observe(c);frame=requestAnimationFrame(draw);const move=(e:PointerEvent)=>{const r=c.getBoundingClientRect();px=(e.clientX-r.left)/r.width;py=(e.clientY-r.top)/r.height;if(reduce.matches)draw(performance.now());};const out=()=>{px=-10;py=-10;};c.addEventListener('pointermove',move);c.addEventListener('pointerleave',out);return()=>{cancelAnimationFrame(frame);redraw.current=null;observer.disconnect();c.removeEventListener('pointermove',move);c.removeEventListener('pointerleave',out);};},[]);
 return <canvas className={`particles ${className}`} ref={ref} aria-label="Interactive violet particle field; move your pointer to displace the particles" role="img"/>;
}
