'use client';
import {useEffect,useRef,useState} from 'react';

import Scene from './Scene';
import AssetLoader from './AssetLoader';
import Particles from './Particles';

import {Header,Footer} from './Shell';
import {useExperience} from './ExperienceProvider';
import CoreArt from './CoreArt';
import {localizedProjects} from '@/lib/project-content';
import Lab from './Lab';
import TechVisual from './TechVisual';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';

export default function Portfolio(){const{locale,theme,t,setTheme,setLocale}=useExperience();const projects=localizedProjects(locale);const stack=['TYPESCRIPT','REACT','NEXT.JS','NODE.JS','POSTGRESQL','THREE.JS'].map((name,i)=>[name,t.stack.categories[i],t.stack.descriptions[i]]);const[openStack,setOpenStack]=useState<number|null>(null),[mode,setMode]=useState(0),[energy,setEnergy]=useState(50),[paused,setPaused]=useState(false),[sound,setSound]=useState(false),[terminal,setTerminal]=useState(false),[command,setCommand]=useState(''),[history,setHistory]=useState<string[]>([]);const cursor=useRef<HTMLDivElement>(null),dot=useRef<HTMLDivElement>(null),audio=useRef<AudioContext|null>(null);
 useEffect(()=>{console.info('Hey developer 👋\nYou found the hidden side of Hanxw.\nTelegram: @hanxw');const reduce=matchMedia('(prefers-reduced-motion: reduce)');let raf=0,x=-100,y=-100,cx=-100,cy=-100;const fine=matchMedia('(pointer: fine)').matches;if(fine&&!reduce.matches)document.documentElement.classList.add('custom-pointer');const move=(e:PointerEvent)=>{x=e.clientX;y=e.clientY;const poster=document.querySelector('.hero-visual .core-art') as HTMLElement;if(poster){poster.style.transform=`perspective(1000px) rotateY(${(x/innerWidth-.5)*10}deg) rotateX(${(.5-y/innerHeight)*7}deg)`;}const el=(e.target as HTMLElement).closest('[data-cursor],a,button');if(cursor.current){cursor.current.dataset.hover=el?'true':'false';cursor.current.textContent=el?.getAttribute('data-cursor')||'';}};const tick=()=>{cx+=(x-cx)*.15;cy+=(y-cy)*.15;if(cursor.current)cursor.current.style.transform=`translate3d(${cx}px,${cy}px,0)`;if(dot.current)dot.current.style.transform=`translate3d(${x}px,${y}px,0)`;raf=requestAnimationFrame(tick);};if(fine&&!reduce.matches){window.addEventListener('pointermove',move);tick();}let secret='';const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,textarea'))return;secret=(secret+e.key.toLowerCase()).slice(-5);if(secret==='hanxw')setTerminal(true);};window.addEventListener('keydown',key);const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');obs.unobserve(e.target);}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>obs.observe(el));const scroll=()=>{document.documentElement.style.setProperty('--scroll',String(scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)));document.body.classList.toggle('scrolled',scrollY>80);const hero=document.querySelector('.hero-visual') as HTMLElement;if(hero&&!reduce.matches&&scrollY<innerHeight)hero.style.transform=`translateY(${scrollY*.12}px) scale(${1+Math.min(scrollY/innerHeight,.8)*.3})`;};window.addEventListener('scroll',scroll,{passive:true});scroll();return()=>{cancelAnimationFrame(raf);obs.disconnect();window.removeEventListener('scroll',scroll);window.removeEventListener('pointermove',move);window.removeEventListener('keydown',key);document.documentElement.classList.remove('custom-pointer');audio.current?.close();};},[]);
 const toggleSound=()=>{if(!audio.current)audio.current=new AudioContext();audio.current.resume();setSound(s=>!s);};const clickSound=()=>{if(!sound||!audio.current)return;const a=audio.current,o=a.createOscillator(),g=a.createGain();o.frequency.value=440;g.gain.setValueAtTime(.025,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.07);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.07);};
 const run=(e:React.FormEvent)=>{e.preventDefault();const c=command.trim().toLowerCase();if(c==='clear')setHistory([]);else {const answers:Record<string,string>={help:'help · about · work · stack · contact · theme dark/light · lang ru/en · clear',about:t.about.body,work:t.commands.workResult,stack:'TypeScript / React / Next.js / Node.js / PostgreSQL / Three.js',contact:'Telegram → https://t.me/hanxw'};if(c.startsWith('theme ')){const v=c.split(' ')[1];if(v==='dark'||v==='light')setTheme(v);}if(c.startsWith('lang ')){const v=c.split(' ')[1];if(v==='en'||v==='ru')setLocale(v);}setHistory(h=>[...h,`hanxw:~$ ${c}`,answers[c]||(c.startsWith('theme ')||c.startsWith('lang ')?'✓':t.commands.unknown)]);}setCommand('');};
 return <><AssetLoader/><a className="skip" href="#work">{t.accessibility.skip}</a><Header/><div ref={cursor} className="cursor"/><div ref={dot} className="cursor-dot"/><div className="scroll-progress"/><main onClick={clickSound}>
 <section id="home" className="hero wrap"><div className="hero-copy"><p className="eyebrow"><i/> <span className="desktop-label">{t.hero.label}</span><span className="mobile-label">{t.hero.label}</span></p><h1><span><b>{t.hero.lines[0]}</b></span><span><b className="gradient">{t.hero.lines[1]}</b></span><span><b>{t.hero.lines[2]}</b></span></h1><div className="hero-after"><p className="hero-description">{t.hero.description}</p><div className="hero-actions"><a href="#work" className="primary">{t.hero.cta} <span>↘</span></a><a href="https://t.me/hanxw" target="_blank" rel="noreferrer" className="telegram"><small>TELEGRAM ↗</small><span>@hanxw</span></a></div></div></div><div className="hero-visual" data-cursor={t.hero.move}><CoreArt hero className="hero-scene"/><div className="hero-live-light"><Scene/></div><span className="core-coordinate mono">{t.hero.coordinate}</span><span className="core-caption mono"><i/> HANXW CORE<br/><span>{t.hero.caption}</span></span><span className="orbit-label mono">[ {t.hero.orbit} ]</span></div><div className="hero-bottom mono"><span>{t.hero.intro}</span><span className="hero-specialty">{t.hero.specialty}</span><a href="#work"><span className="scroll-full">{t.hero.scroll}</span><span className="scroll-short">{t.hero.scrollShort}</span> <span className="scroll-arrow">↓</span></a></div></section>
 <section id="work" className="work wrap section"><div className="section-top"><p className="eyebrow">{t.projects.label}</p><span className="mono muted">{t.projects.meta}</span></div><div className="section-intro reveal"><h2>{t.projects.headline[0]}<br/><span className="outline">{t.projects.headline[1]}</span></h2><p>{t.projects.intro}</p></div><div className="project-list">{projects.map((p,i)=><article className={`project project-${i+1} reveal`} key={p.slug}><a href={`/${locale}/work/${p.slug}`} className="project-media" data-cursor={t.projects.view} style={{viewTransitionName:`project-${p.slug}`}}>{i===0?<><CoreArt/><div className="project-brand">CORE<span>001</span></div><span className="media-corner mono">{t.projects.media}</span></>:i===1?<><Particles mode={1}/><div className="particle-title">{t.projects.order}<br/><em>{t.projects.chaos}</em></div></>:<><Particles mode={2}/><div className="chromatic-title">CHROMATIC<span>{t.projects.lightStudy}</span></div></>}<span className="media-arrow">↗</span></a><div className="project-info"><span className="mono muted">{p.index} / {String(projects.length).padStart(2,'0')} — {p.kind}</span><div><h3><a href={`/${locale}/work/${p.slug}`}>{p.title}</a></h3><p>{p.shortDescription}</p></div><span className="project-stack mono">{p.stack.join(' / ')}<br/><a href={`/${locale}/work/${p.slug}`}>{t.projects.open} ↗</a></span></div></article>)}</div></section>
 <section id="about" className="about wrap section"><p className="eyebrow">{t.about.label}</p><div className="about-layout"><div className="about-copy reveal"><h2>{t.about.headline[0]}<br/>{t.about.headline[1]}</h2><p className="body-large">{t.about.body}</p><p className="muted about-small">{t.about.detail}</p><div className="about-tags mono">{t.about.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div><div className="about-visual"><Scene variant="h"/><span className="mono">{t.about.caption}</span></div></div></section>
 <section className="philosophy wrap"><p className="eyebrow">{t.about.philosophy}</p><p className="muted reveal">{t.about.not[0]}<br/>{t.about.not[1]}</p><h2 className="reveal">{t.about.yes[0]}<br/><span className="gradient">{t.about.yes[1]}</span></h2></section>
 <section id="stack" className="stack wrap section"><div className="section-top"><p className="eyebrow">{t.stack.label}</p><span className="mono muted">{t.stack.meta}</span></div><h2 className="reveal">{t.stack.headline}</h2><div className="stack-list">{stack.map(([name,category,desc],i)=><div className={`stack-item ${openStack===i?'expanded':''}`} key={name}><button className="stack-row" onClick={()=>setOpenStack(openStack===i?null:i)} aria-expanded={openStack===i} aria-controls={`stack-${i}`}><span className="mono">0{i+1}</span><strong>{name}</strong><span className="mono stack-category">{category}</span><span className="stack-arrow">{openStack===i?'−':'↗'}</span></button><div className="stack-detail" id={`stack-${i}`} hidden={openStack!==i}><p>{desc}</p><TechVisual index={i}/></div></div>)}</div></section>
 <div className="marquee" aria-hidden="true"><div>{[...t.stack.marquee,...t.stack.marquee].map((word,i)=><span key={i}>{word} <i>✳</i> </span>)}</div></div>
 <section className="process wrap section"><div><p className="eyebrow">{t.process.label}</p><h2>{t.process.headline[0]}<br/>{t.process.headline[1]}</h2></div><div className="process-steps">{t.process.titles.map((n,i)=>[n,t.process.descriptions[i]]).map(([n,d],i)=><article className="process-step reveal" key={n}><span className="mono violet">0{i+1}</span><div><h3>{n}</h3><p>{d}</p></div></article>)}</div></section>
 <Lab/>
 <section id="contact" className="contact wrap section"><div className="section-top"><p className="eyebrow">{t.contact.label}</p><span className="mono muted">{t.contact.meta}</span></div><div className="contact-content"><div><p className="mono">{t.contact.idea}</p><h2>{t.contact.headline[0]}<br/>{t.contact.headline[1]}<br/><span className="outline">{t.contact.headline[2]}</span></h2></div><div className="contact-action"><div className="contact-core"><Scene/></div><a href="https://t.me/hanxw" target="_blank" rel="noreferrer" className="contact-circle">{t.contact.cta[0]}<br/>{t.contact.cta[1]}<span>↗</span></a><a href="https://t.me/hanxw" target="_blank" rel="noreferrer" className="contact-handle"><small className="mono">{t.contact.telegram}</small><strong>@hanxw ↗</strong></a></div></div></section>
 </main><Footer/><button className={`sound-toggle mono ${sound?'enabled':''}`} onClick={toggleSound} aria-pressed={sound}>{t.footer.sound} {sound?t.footer.on:t.footer.off} <span>▥</span></button><Dialog open={terminal} onOpenChange={setTerminal}><DialogContent className="terminal" showCloseButton={false}><button className="modal-close" onClick={()=>setTerminal(false)} aria-label={t.accessibility.close}>×</button><DialogTitle className="mono violet">{t.commands.terminal}</DialogTitle><DialogDescription className="mono">{t.commands.terminalDescription}</DialogDescription><div className="terminal-output" aria-live="polite"><p>{t.commands.welcome}</p>{history.map((h,i)=><p key={i}>{h}</p>)}</div><form onSubmit={run}><label htmlFor="command">hanxw:~$</label><input id="command" value={command} onChange={e=>setCommand(e.target.value)} autoComplete="off" spellCheck={false}/><button type="submit">↵</button></form></DialogContent></Dialog></>}
