'use client';
import {useEffect,useRef,useState} from 'react';
const vertex=`attribute vec2 position;void main(){gl_Position=vec4(position,0.,1.);}`;
const fragment=`precision highp float;
uniform vec2 resolution;uniform vec2 pointer;uniform float time;uniform float mode;uniform float energy;
#define PI 3.14159265
mat2 rot(float a){return mat2(cos(a),-sin(a),sin(a),cos(a));}
float noise(vec3 p){return sin(p.x*5.3+sin(p.y*4.))*sin(p.y*3.7+sin(p.z*5.))*sin(p.z*4.2+sin(p.x*3.));}
float box(vec3 p,vec3 b){vec3 q=abs(p)-b;return length(max(q,0.))+min(max(q.x,max(q.y,q.z)),0.);}
float shape(vec3 p){p.xz*=rot(pointer.x*.15+time*.045);p.yz*=rot(pointer.y*.1);if(mode>1.5){float a=box(p-vec3(.48,0.,0.),vec3(.18,.85,.24));float b=box(p+vec3(.48,0.,0.),vec3(.18,.85,.24));float c=box(p,vec3(.48,.17,.24));return min(min(a,b),c)-.08;}return length(p)-(1.+noise(p*1.6+time*.055)*.045);}
float scene(vec3 p){return shape(p);}
vec3 normal(vec3 p){vec2 e=vec2(.003,0);return normalize(vec3(scene(p+e.xyy)-scene(p-e.xyy),scene(p+e.yxy)-scene(p-e.yxy),scene(p+e.yyx)-scene(p-e.yyx)));}
void main(){vec2 uv=(gl_FragCoord.xy-.5*resolution)/resolution.y;vec3 bg=vec3(.0196,.0196,.0275);float halo=exp(-length(uv-vec2(.1,0.))*4.);vec3 col=bg+vec3(.07,.025,.14)*halo;vec3 ro=vec3(0.,0.,3.65);vec3 rd=normalize(vec3(uv*2.55,-3.));float t=0.;bool hit=false;vec3 p;for(int i=0;i<64;i++){p=ro+rd*t;float d=scene(p);if(d<.003){hit=true;break;}t+=d*.8;if(t>7.)break;}if(hit){vec3 n=normal(p);vec3 refl=reflect(rd,n);float fres=pow(1.-max(dot(n,-rd),0.),3.);vec3 light=normalize(vec3(-1.,1.2,1.));float spec=pow(max(dot(refl,light),0.),30.);float strip=pow(max(0.,1.-abs(refl.y-.5)),55.);float spec2=pow(max(dot(refl,normalize(vec3(1.,-.2,1.))),0.),15.);float veins=pow(1.-abs(sin((p.y*2.7+noise(p*1.45)*.43)*6.)),30.);col=vec3(.02,.022,.035)+vec3(.35,.38,.55)*spec+vec3(.6,.6,.78)*strip+vec3(.2,.08,.75)*spec2+fres*vec3(.2,.075,.5);col+=veins*vec3(.42,.12,1.)*.7*energy;}vec2 q=uv;q*=rot(-.35);float r=length(vec2(q.x,q.y*3.25));float ring=exp(-abs(r-.96)*400.);float ring2=exp(-abs(r-1.04)*550.);float front=(1.-smoothstep(-.05,.08,q.y));if(!hit||front>.6)col+=vec3(.48,.27,.82)*ring*.8+vec3(.27,.23,.49)*ring2*.4;float grain=fract(sin(dot(gl_FragCoord.xy,vec2(12.9898,78.233)))*43758.5453);col+=(grain-.5)*.008;gl_FragColor=vec4(col,1.);}`;
export default function Scene({variant='core',className='',interactive=true}:{variant?:'core'|'h',className?:string,interactive?:boolean}){
 const ref=useRef<HTMLCanvasElement>(null);const[failed,setFailed]=useState(false);
 useEffect(()=>{const c=ref.current;if(!c)return;const gl=c.getContext('webgl',{alpha:false,antialias:false,powerPreference:'low-power'});if(!gl){setFailed(true);return;}let program:WebGLProgram|null=null;let buffer:WebGLBuffer|null=null;const shaders:WebGLShader[]=[];let raf=0,visible=true,dead=false;const reduce=matchMedia('(prefers-reduced-motion: reduce)');
 try{program=gl.createProgram()!;for(const[type,source]of [[gl.VERTEX_SHADER,vertex],[gl.FRAGMENT_SHADER,fragment]] as const){const s=gl.createShader(type)!;shaders.push(s);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)||'shader');gl.attachShader(program,s);}gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('link');gl.useProgram(program);buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const pos=gl.getAttribLocation(program,'position');gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,0,0);}catch{shaders.forEach(s=>gl.deleteShader(s));gl.deleteProgram(program);setFailed(true);return;}
 const res=gl.getUniformLocation(program!,'resolution'),tim=gl.getUniformLocation(program!,'time'),ptr=gl.getUniformLocation(program!,'pointer'),mod=gl.getUniformLocation(program!,'mode'),eng=gl.getUniformLocation(program!,'energy');let x=0,y=0,tx=0,ty=0;const start=performance.now();
 const render=(now:number)=>{if(dead)return;raf=requestAnimationFrame(render);if(!visible||document.hidden)return;const dpr=Math.min(devicePixelRatio,innerWidth<768?1:1.35);const w=Math.round(c.clientWidth*dpr),h=Math.round(c.clientHeight*dpr);if(c.width!==w||c.height!==h){c.width=w;c.height=h;gl.viewport(0,0,w,h);}x+=(tx-x)*.035;y+=(ty-y)*.035;gl.uniform2f(res,w,h);gl.uniform2f(ptr,reduce.matches?0:x,reduce.matches?0:y);gl.uniform1f(tim,reduce.matches?0:(now-start)/1000);gl.uniform1f(mod,variant==='h'?2:0);gl.uniform1f(eng,1);gl.drawArrays(gl.TRIANGLES,0,6);if(reduce.matches)cancelAnimationFrame(raf);};raf=requestAnimationFrame(render);
 const move=(e:PointerEvent)=>{const r=c.getBoundingClientRect();tx=(e.clientX-r.left)/r.width*2-1;ty=(e.clientY-r.top)/r.height*2-1;};if(interactive)c.addEventListener('pointermove',move);const obs=new IntersectionObserver(([e])=>{visible=e.isIntersecting;if(visible&&reduce.matches)render(performance.now());},{rootMargin:'100px'});obs.observe(c);const lost=(e:Event)=>{e.preventDefault();setFailed(true);};c.addEventListener('webglcontextlost',lost);return()=>{dead=true;cancelAnimationFrame(raf);obs.disconnect();c.removeEventListener('pointermove',move);c.removeEventListener('webglcontextlost',lost);gl.deleteBuffer(buffer);shaders.forEach(s=>gl.deleteShader(s));gl.deleteProgram(program);};},[variant,interactive]);
 return <div className={`scene ${className}`} aria-hidden="true">{failed?<img src="/core.webp" alt=""/>:<canvas ref={ref}/>}</div>
}
